const data = {
    "terms": [
      {"s": "P","l": "G10","t": "d","f": "Scalar Quantity","b": "A quantity with magnitude only (e.g., mass, speed)."
      },
      {"s": "P","l": "G10","t": "d","f": "Vector Quantity","b": "A quantity with both magnitude and direction (e.g., force, velocity)."
      },
      {"s": "P","l": "G10","t": "Formula","f": "Speed","b": "Speed = Distance / Time (units: m/s)."},
      {"s": "P","l": "G10","t": "Formula","f": "Acceleration","b": "a = (v - u) / t (units: m/s²)."},
      {"s": "P","l": "G10","t": "l","f": "Newton's First Law","b": "An object remains at rest/uniform motion unless acted upon by a net force."},
      {"s": "P","l": "G10","t": "l","f": "Newton's Second Law","b": "F = ma (Force = mass × acceleration)."},
      {"s": "P","l": "G10","t": "l","f": "Newton's Third Law","b": "Every action has an equal and opposite reaction."},
      {"s": "P","l": "G10","t": "d","f": "Momentum","b": "p = mv (units: kg·m/s)."},
      {"s": "P","l": "G10","t": "Principle","f": "Conservation of Momentum","b": "Total momentum before a collision equals total momentum after (in a closed system)."
      },
      {"s": "P",
        "l": "G10",
        "t": "d",
        "f": "Density",
        "b": "ρ = m/V (units: kg/m³)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Pressure",
        "b": "P = F/A (units: Pascals, Pa)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "l",
        "f": "Pascal's Principle",
        "b": "Pressure applied to a fluid is transmitted equally in all directions."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Buoyant Force",
        "b": "Upward force exerted by a fluid on an immersed object (Archimedes' Principle)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Work",
        "b": "W = Fd (units: Joules, J)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Power",
        "b": "P = W/t (units: Watts, W)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Energy Efficiency",
        "b": "(Useful energy output / Total energy input) × 100%."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Conduction",
        "b": "Heat transfer through a material without the material itself moving."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Radiation",
        "b": "Heat transfer via electromagnetic waves (e.g., infrared)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Specific Heat Capacity",
        "b": "Energy required to raise 1 kg of a substance by 1°C (units: J/kg°C)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Latent Heat",
        "b": "Energy absorbed/released during a phase change without temperature change."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Wave",
        "b": "Oscillation that transfers energy without transferring matter."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Transverse Wave",
        "b": "Wave where oscillations are perpendicular to the direction of energy transfer (e.g., light)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Longitudinal Wave",
        "b": "Wave where oscillations are parallel to the direction of energy transfer (e.g., sound)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Amplitude",
        "b": "Maximum displacement of a wave from its rest position."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Wavelength",
        "b": "Distance between two consecutive wave crests/troughs (units: meters)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Frequency",
        "b": "Number of wave cycles per second (units: Hertz, Hz)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "Formula",
        "f": "Wave Speed",
        "b": "v = fλ (Wave speed = frequency × wavelength)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Reflection",
        "b": "Wave bounces off a surface (angle of incidence = angle of reflection)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Refraction",
        "b": "Wave changes direction when passing into a different medium (due to speed change)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Diffraction",
        "b": "Wave spreads out after passing through a gap/around an obstacle."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Electromagnetic Spectrum",
        "b": "Range of all electromagnetic waves (radio → gamma rays)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Current",
        "b": "Flow of electric charge (units: Amperes, A)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Voltage",
        "b": "Electrical potential difference (units: Volts, V)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Resistance",
        "b": "Opposition to current flow (units: Ohms, Ω)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "l",
        "f": "Ohm's Law",
        "b": "V = IR (Voltage = Current × Resistance)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Series Circuit",
        "b": "Components connected in a single loop (current same everywhere)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Parallel Circuit",
        "b": "Components connected in branches (voltage same across each branch)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Magnetic Field",
        "b": "Region around a magnet where magnetic forces act."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Electromagnet",
        "b": "Magnet created by electric current in a coil (strength depends on current/turns)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Solenoid",
        "b": "Coil of wire that acts as a magnet when current flows."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Fleming's Left-Hand Rule",
        "b": "Thumb = Force, Index = Field, Middle = Current (for motors)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Fleming's Right-Hand Rule",
        "b": "Thumb = Motion, Index = Field, Middle = Current (for generators)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Transformer",
        "b": "Device that changes AC voltage (Vs/Vp = Ns/Np)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Step-Up Transformer",
        "b": "Increases voltage (more secondary turns)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Step-Down Transformer",
        "b": "Decreases voltage (fewer secondary turns)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Diode",
        "b": "Component that allows current to flow in one direction only."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "LED",
        "b": "Light-Emitting Diode (emits light when current passes)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Thermistor",
        "b": "Resistor whose resistance decreases with temperature."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "LDR",
        "b": "Light-Dependent Resistor (resistance decreases with light intensity)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Half-Life",
        "b": "Time taken for half the radioactive nuclei in a sample to decay."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Alpha Particle",
        "b": "Helium nucleus (2 protons + 2 neutrons) emitted during radioactive decay."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Beta Particle",
        "b": "High-speed electron emitted during radioactive decay."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Gamma Radiation",
        "b": "High-energy electromagnetic wave emitted during radioactive decay."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Nuclear Fission",
        "b": "Splitting of a heavy nucleus into smaller nuclei, releasing energy (e.g., in reactors)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Nuclear Fusion",
        "b": "Combining light nuclei to form a heavier nucleus, releasing energy (e.g., in stars)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Renewable Energy",
        "b": "Energy from sources that replenish naturally (e.g., solar, wind)."
      },
      {
        "s": "P",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Non-Renewable Energy",
        "b": "Energy from finite sources (e.g., fossil fuels, nuclear)."
      },
  
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Atom",
        "b": "Smallest unit of an element that retains its properties."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Proton",
        "b": "Positively charged subatomic particle in the nucleus (mass = 1 amu)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Neutron",
        "b": "Neutral subatomic particle in the nucleus (mass = 1 amu)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Electron",
        "b": "Negatively charged subatomic particle orbiting the nucleus (mass ≈ 0)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Atomic Number",
        "b": "Number of protons in an atom (defines the element)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Mass Number",
        "b": "Sum of protons and neutrons in an atom."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Isotopes",
        "b": "Atoms of the same element with different neutron numbers (e.g., Carbon-12 vs. Carbon-14)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Ion",
        "b": "Charged atom (formed by gaining/losing electrons)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Cation",
        "b": "Positively charged ion (lost electrons)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Anion",
        "b": "Negatively charged ion (gained electrons)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Ionic Bond",
        "b": "Electrostatic attraction between oppositely charged ions (e.g., NaCl)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Covalent Bond",
        "b": "Shared pair of electrons between atoms (e.g., H₂O)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Metallic Bond",
        "b": "Bond between metal ions and delocalized electrons."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Periodic Table",
        "b": "Tabular arrangement of elements by increasing atomic number and properties."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Group",
        "b": "Vertical column in the periodic table (elements share similar properties)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Period",
        "b": "Horizontal row in the periodic table."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Alkali Metals",
        "b": "Group 1 elements (e.g., Li, Na, K) — highly reactive, form +1 ions."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Halogens",
        "b": "Group 17 elements (e.g., F, Cl, Br) — reactive nonmetals, form -1 ions."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Noble Gases",
        "b": "Group 18 elements (e.g., He, Ne, Ar) — inert, full outer electron shells."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Transition Metals",
        "b": "Elements in groups 3-12 (e.g., Fe, Cu) — form colored compounds/variable oxidation states."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Mole",
        "b": "Unit of amount of substance (6.022 × 10²³ particles)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "Formula",
        "f": "Molar Mass",
        "b": "Mass of one mole of a substance (units: g/mol)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "Formula",
        "f": "Number of Moles",
        "b": "n = mass (g) / molar mass (g/mol)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Empirical Formula",
        "b": "Simplest whole-number ratio of atoms in a compound."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Molecular Formula",
        "b": "Actual number of atoms in a compound (e.g., C₆H₁₂O₆ for glucose)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Chemical Reaction",
        "b": "Process where substances (reactants) transform into new substances (products)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Exothermic Reaction",
        "b": "Reaction that releases heat (e.g., combustion)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Endothermic Reaction",
        "b": "Reaction that absorbs heat (e.g., photosynthesis)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Combustion",
        "b": "Reaction with oxygen, releasing heat/light (e.g., burning fuels)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Oxidation",
        "b": "Loss of electrons/gain of oxygen."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Reduction",
        "b": "Gain of electrons/loss of oxygen."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Redox Reaction",
        "b": "Reaction where oxidation and reduction occur simultaneously."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Acid",
        "b": "Substance that donates H⁺ ions (pH < 7)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Base",
        "b": "Substance that accepts H⁺ ions (pH > 7)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Alkali",
        "b": "Soluble base (e.g., NaOH)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "pH Scale",
        "b": "Measures acidity/basicity (0-14; 7 = neutral)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Neutralization",
        "b": "Reaction between acid and base to form salt + water."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Salt",
        "b": "Ionic compound formed from acid-base neutralization (e.g., NaCl)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Electrolysis",
        "b": "Decomposition of a compound using electricity (e.g., water → H₂ + O₂)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Anode",
        "b": "Positive electrode (oxidation occurs here)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Cathode",
        "b": "Negative electrode (reduction occurs here)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Organic C",
        "b": "Study of carbon-containing compounds."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Hydrocarbon",
        "b": "Compound containing only hydrogen and carbon."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Alkane",
        "b": "Saturated hydrocarbon with single bonds (CₙH₂ₙ₊₂)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Alkene",
        "b": "Unsaturated hydrocarbon with double bonds (CₙH₂ₙ)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Alkyne",
        "b": "Unsaturated hydrocarbon with triple bonds (CₙH₂ₙ₋₂)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Isomer",
        "b": "Compounds with the same molecular formula but different structures."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Polymer",
        "b": "Large molecule made of repeating monomers (e.g., plastics)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Monomer",
        "b": "Small molecule that combines to form a polymer."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Fermentation",
        "b": "Anaerobic conversion of sugars into alcohol/CO₂ by yeast."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Catalyst",
        "b": "Substance that speeds up a reaction without being consumed."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Reversible Reaction",
        "b": "Reaction where products can revert to reactants (⇌ symbol)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Equilibrium",
        "b": "State where forward/reverse reaction rates are equal (dynamic balance)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Haber Process",
        "b": "Industrial synthesis of ammonia: N₂ + 3H₂ ⇌ 2NH₃ (high pressure, Fe catalyst)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Contact Process",
        "b": "Industrial production of sulfuric acid (V₂O₅ catalyst)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Alloy",
        "b": "Mixture of metals (e.g., steel = iron + carbon)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Corrosion",
        "b": "Deterioration of metals by oxidation (e.g., rusting of iron)."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Rusting",
        "b": "Corrosion of iron: 4Fe + 3O₂ + 6H₂O → 4Fe(OH)₃."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Greenhouse Effect",
        "b": "Trapping of heat by atmospheric gases (CO₂, CH₄) leading to global warming."
      },
      {
        "s": "C",
        "c": "IGCSE",
        "l": "G10",
        "t": "d",
        "f": "Chlorofluorocarbons (CFCs)",
        "b": "Compounds that deplete the ozone layer (now banned)."
      },
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2x + 5 = 13", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3x - 7 = 11", "b": "x = 6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5 - 4x = 17", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/3 + 2 = 5", "b": "x = 9"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2(x + 3) = 10", "b": "x = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 4x + 9 = 25", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 7 - 3x = 16", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/5 - 1 = 3", "b": "x = 20"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3(x - 2) = 12", "b": "x = 6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5x + 2 = 17", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 6x - 11 = 25", "b": "x = 6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 8 + 2x = 14", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/2 - 4 = 1", "b": "x = 10"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 4(x + 1) = 20", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 9 - 5x = 24", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 7x + 3 = 31", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/4 + 5 = 7", "b": "x = 8"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2x - 9 = 5", "b": "x = 7"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3x + 8 = 20", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5(x - 1) = 15", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 10 - 6x = 28", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/6 + 2 = 4", "b": "x = 12"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 4x - 5 = 11", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2(x + 4) = 14", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 7x - 10 = 18", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/3 - 1 = 2", "b": "x = 9"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 6 + 3x = 21", "b": "x = 5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5x - 3 = 12", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 4 - 2x = 10", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/5 + 3 = 7", "b": "x = 20"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3(x + 2) = 15", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 8x + 4 = 20", "b": "x = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 12 - 5x = 27", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/2 + 6 = 10", "b": "x = 8"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 6x + 7 = 25", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2x - 3 = 7", "b": "x = 5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 9 + 4x = 25", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/4 - 2 = 1", "b": "x = 12"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5(x - 3) = 10", "b": "x = 5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 7x + 5 = 26", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3 - 6x = 15", "b": "x = -2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/6 - 4 = 2", "b": "x = 36"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 4x + 6 = 18", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2(x - 5) = 4", "b": "x = 7"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 8x - 9 = 15", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/3 + 4 = 7", "b": "x = 9"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5x + 8 = 23", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 10 - 4x = 22", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3x - 2 = 13", "b": "x = 5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/5 + 1 = 4", "b": "x = 15"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 6(x + 1) = 24", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 7x - 4 = 17", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2 + 5x = 22", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/2 - 3 = 2", "b": "x = 10"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 4x + 3 = 19", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 9 - 3x = 18", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 6x + 2 = 20", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/4 + 3 = 6", "b": "x = 12"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3(x - 4) = 9", "b": "x = 7"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5x - 7 = 13", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 8 + 6x = 32", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/6 + 1 = 3", "b": "x = 12"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2x - 8 = 6", "b": "x = 7"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 4(x + 2) = 16", "b": "x = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 7x + 6 = 27", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 10 - 7x = 31", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/3 + 5 = 8", "b": "x = 9"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5x + 9 = 24", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3x - 5 = 10", "b": "x = 5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/5 - 2 = 1", "b": "x = 15"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 6(x - 2) = 18", "b": "x = 5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 4x + 7 = 23", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 9 - 4x = 21", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2x + 10 = 18", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/2 + 2 = 5", "b": "x = 6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3(x + 3) = 21", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5x - 8 = 12", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 7 + 2x = 15", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/4 - 1 = 2", "b": "x = 12"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 6x + 1 = 19", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2(x - 6) = 8", "b": "x = 10"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 8x - 3 = 21", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/3 - 3 = 1", "b": "x = 12"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 4x + 8 = 24", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5 - 7x = 26", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3x + 4 = 16", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/5 + 2 = 6", "b": "x = 20"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2(x + 5) = 18", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 6x - 5 = 13", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 9 + 3x = 24", "b": "x = 5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/2 - 5 = 0", "b": "x = 10"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 4x - 6 = 10", "b": "x = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 7x + 2 = 23", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 3 - 5x = 18", "b": "x = -3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: x/6 + 3 = 5", "b": "x = 12"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 5x + 6 = 21", "b": "x = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "x", "f": "x: 2x - 4 = 8", "b": "x = 6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: x + y = 5 and 2x - y = 4", "b": "x = 3, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 3x + 2y = 8 and x - y = 1", "b": "x = 2, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 4x + y = 10 and 2x - y = 2", "b": "x = 2, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 5x - 3y = 1 and x + y = 3", "b": "x = 1, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 2x + 3y = 12 and x - 2y = -1", "b": "x = 3, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 7x - 2y = 13 and 3x + y = 9", "b": "x = 2, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: x + 4y = 10 and 2x - y = 5", "b": "x = 4, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 3x - y = 7 and x + 2y = 6", "b": "x = 3, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 5x + y = 12 and 2x - 3y = 1", "b": "x = 2, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 4x + 3y = 15 and x - y = 2", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 2x + y = 7 and 3x - 2y = 4", "b": "x = 2, y = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: x - 3y = 1 and 4x + y = 13", "b": "x = 4, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 6x - y = 17 and 2x + y = 7", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 3x + 4y = 19 and x - y = 1", "b": "x = 3, y = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 5x - 2y = 11 and x + 3y = 7", "b": "x = 2, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 2x + 5y = 16 and 3x - y = 5", "b": "x = 3, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 4x - 3y = 5 and x + 2y = 6", "b": "x = 2, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: x + y = 8 and 2x - y = 4", "b": "x = 4, y = 4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 3x + y = 10 and 2x - y = 5", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 5x - y = 14 and x + 2y = 5", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 2x + 3y = 13 and 4x - y = 7", "b": "x = 2, y = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: x - 2y = 3 and 3x + y = 11", "b": "x = 4, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 6x + 2y = 20 and 3x - y = 7", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 4x + y = 13 and 2x - 3y = 1", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 5x - 4y = 6 and x + y = 3", "b": "x = 2, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 2x + y = 9 and 3x - 2y = 4", "b": "x = 2, y = 5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: x - y = 2 and 4x + 3y = 17", "b": "x = 4, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 3x + 5y = 19 and x - y = 1", "b": "x = 3, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 6x - y = 15 and 2x + y = 7", "b": "x = 2, y = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 4x + 2y = 14 and x - y = 1", "b": "x = 3, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 5x - 3y = 7 and 2x + y = 6", "b": "x = 2, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 3x + y = 11 and x - 2y = 1", "b": "x = 3, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 2x - 5y = 1 and 4x + y = 13", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: x + 3y = 10 and 2x - y = 5", "b": "x = 4, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 5x + 2y = 17 and 3x - y = 7", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 4x - y = 11 and x + 2y = 7", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 2x + 4y = 14 and 3x - y = 5", "b": "x = 2, y = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: x - 3y = 2 and 5x + y = 14", "b": "x = 4, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 6x - 2y = 16 and 2x + y = 7", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 3x + 2y = 13 and x - y = 2", "b": "x = 3, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 5x - y = 12 and 2x + 3y = 11", "b": "x = 2, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 4x + y = 15 and 2x - y = 5", "b": "x = 3, y = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: x + 2y = 7 and 3x - y = 8", "b": "x = 3, y = 2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 5x - 2y = 9 and x + y = 3", "b": "x = 2, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 2x + 3y = 11 and 4x - y = 7", "b": "x = 2, y = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: x - y = 3 and 3x + 2y = 14", "b": "x = 4, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 6x + y = 19 and 2x - 3y = 1", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 4x - 2y = 10 and x + y = 4", "b": "x = 3, y = 1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 3x + y = 12 and 2x - y = 6", "b": "x = 3, y = 3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "xy", "f": "Solve: 5x - 3y = 8 and x + 2y = 5", "b": "x = 2, y = 1"},
      
          // 3. s of the Formula (30 questions)
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = 2x + 3", "b": "x = (y - 3)/2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 3x - y = 5", "b": "x = (y + 5)/3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = x/4 - 2", "b": "x = 4(y + 2)"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 2y = 5x - 1", "b": "x = (2y + 1)/5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = 3 - 2x", "b": "x = (3 - y)/2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 4y = 3x + 7", "b": "x = (4y - 7)/3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = 5x + 2", "b": "x = (y - 2)/5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 6x - y = 9", "b": "x = (y + 9)/6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = x/3 + 4", "b": "x = 3(y - 4)"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 2x + y = 8", "b": "x = (8 - y)/2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = 4 - 3x", "b": "x = (4 - y)/3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 5y = 2x - 3", "b": "x = (5y + 3)/2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = 6x + 1", "b": "x = (y - 1)/6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 3x - 2y = 7", "b": "x = (2y + 7)/3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = x/5 - 1", "b": "x = 5(y + 1)"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 4x + y = 12", "b": "x = (12 - y)/4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = 2 - 4x", "b": "x = (2 - y)/4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 3y = 5x + 4", "b": "x = (3y - 4)/5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = 7x - 2", "b": "x = (y + 2)/7"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 2x - 3y = 6", "b": "x = (3y + 6)/2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = x/2 + 3", "b": "x = 2(y - 3)"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 5x + 2y = 10", "b": "x = (10 - 2y)/5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = 3x - 5", "b": "x = (y + 5)/3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 4y = x + 6", "b": "x = 4y - 6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = 5 - 6x", "b": "x = (5 - y)/6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 3x + 4y = 15", "b": "x = (15 - 4y)/3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = x/6 + 2", "b": "x = 6(y - 2)"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 2x - y = 4", "b": "x = (y + 4)/2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: y = 4x + 3", "b": "x = (y - 3)/4"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s of the Formula", "f": "Make x the s: 5y = 3x - 2", "b": "x = (5y + 2)/3"},
      
          // 4. wp (20 questions)
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A number increased by 7 is 15. What is the number?", "b": "8"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "Two numbers add to 20, and their difference is 4. Find the numbers.", "b": "12 and 8"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A rectangle’s length is twice its width. If the perimeter is 24 cm, find the width.", "b": "4 cm"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A shop sells pens for R5 each. If 3 pens cost R15, how much for 7 pens?", "b": "R35"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A car travels 120 km in 2 hours. What is its speed?", "b": "60 km/h"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A book costs R50 more than a pen. Together they cost R130. Find the pen’s cost.", "b": "R40"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A number decreased by 3 is 12. What is the number?", "b": "15"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "The sum of two consecutive numbers is 27. Find the smaller number.", "b": "13"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A shirt costs R20 less than a jacket. Together they cost R100. Find the shirt’s cost.", "b": "R40"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A train travels 150 km in 3 hours. What is its speed?", "b": "50 km/h"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A number tripled is 24. What is the number?", "b": "8"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "Two numbers add to 15, and one is twice the other. Find the smaller number.", "b": "5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A rectangle’s width is 3 cm less than its length. If the perimeter is 18 cm, find the length.", "b": "6 cm"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A bag of apples costs R30. If 5 apples cost R15, how many apples in the bag?", "b": "10"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A number divided by 4 is 6. What is the number?", "b": "24"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "The sum of three consecutive numbers is 36. Find the smallest number.", "b": "11"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A phone costs R100 more than a charger. Together they cost R250. Find the charger’s cost.", "b": "R75"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A boat travels 80 km in 4 hours. What is its speed?", "b": "20 km/h"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "A number doubled and increased by 5 is 17. What is the number?", "b": "6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "wp", "f": "Two numbers differ by 6 and sum to 20. Find the larger number.", "b": "13"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √18", "b": "3√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √50", "b": "5√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √12 + √3", "b": "3√3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 2√8", "b": "4√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √27", "b": "3√3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √75", "b": "5√3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √32", "b": "4√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √48", "b": "4√3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 3√12", "b": "6√3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √20", "b": "2√5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √45", "b": "3√5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √72", "b": "6√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 2√18", "b": "6√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √98", "b": "7√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √24", "b": "2√6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √80", "b": "4√5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 4√27", "b": "12√3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √125", "b": "5√5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √54", "b": "3√6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 2√50", "b": "10√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √63", "b": "3√7"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √28", "b": "2√7"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 3√32", "b": "12√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √108", "b": "6√3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √44", "b": "2√11"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √150", "b": "5√6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 2√45", "b": "6√5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √200", "b": "10√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √99", "b": "3√11"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 5√8", "b": "10√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √112", "b": "4√7"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √36", "b": "6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 3√20", "b": "6√5"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √162", "b": "9√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √88", "b": "4√11"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 2√72", "b": "12√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √147", "b": "7√3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √40", "b": "2√10"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 4√18", "b": "12√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √128", "b": "8√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √90", "b": "3√10"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 2√75", "b": "10√3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √175", "b": "5√7"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √52", "b": "2√13"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 3√48", "b": "12√3"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √68", "b": "2√17"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √135", "b": "3√15"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: 2√98", "b": "14√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √162", "b": "9√2"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "s", "f": "Simplify: √108", "b": "6√3"},
      
          // 6. e (100 questions)
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^3 × 2^2", "b": "2^5 = 32"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 5^4 ÷ 5^2", "b": "5^2 = 25"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (3^2)^3", "b": "3^6 = 729"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^0", "b": "1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^-3", "b": "1/8"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^3 × 10^-1", "b": "10^2 = 100"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^5 ÷ 3^2", "b": "3^3 = 27"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (2^4)^2", "b": "2^8 = 256"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 6^-2", "b": "1/36"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^3 × 4^-1", "b": "4^2 = 16"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 7^2 ÷ 7^1", "b": "7^1 = 7"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (5^3)^2", "b": "5^6 = 15625"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^0", "b": "1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^4 × 2^3", "b": "2^7 = 128"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 8^-1", "b": "1/8"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^4 ÷ 10^2", "b": "10^2 = 100"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (4^2)^3", "b": "4^6 = 4096"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 5^-3", "b": "1/125"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^3 × 3^2", "b": "3^5 = 243"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 6^2 ÷ 6^1", "b": "6^1 = 6"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (2^5)^2", "b": "2^10 = 1024"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 7^-2", "b": "1/49"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^4 × 4^-2", "b": "4^2 = 16"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^5 ÷ 10^3", "b": "10^2 = 100"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (3^4)^2", "b": "3^8 = 6561"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^-4", "b": "1/16"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 5^3 × 5^2", "b": "5^5 = 3125"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 6^0", "b": "1"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^5 ÷ 4^3", "b": "4^2 = 16"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (7^2)^3", "b": "7^6 = 117649"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^-5", "b": "1/243"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^6 × 2^-2", "b": "2^4 = 16"},
          {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^2 ÷ 10^1", "b": "10^1 = 10"},
              // 6. e (Continuing from #34 to #100, 66 remaining)
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (5^2)^4", "b": "5^8 = 390625"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^-3", "b": "1/64"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^4 × 3^-1", "b": "3^3 = 27"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 6^3 ÷ 6^2", "b": "6^1 = 6"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (2^3)^3", "b": "2^9 = 512"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^-2", "b": "1/100"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 7^4 × 7^-2", "b": "7^2 = 49"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 5^6 ÷ 5^3", "b": "5^3 = 125"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (4^3)^2", "b": "4^6 = 4096"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^5 × 2^2", "b": "2^7 = 128"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^-4", "b": "1/81"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 6^4 ÷ 6^2", "b": "6^2 = 36"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (10^2)^3", "b": "10^6 = 1000000"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 5^0", "b": "1"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^2 × 4^3", "b": "4^5 = 1024"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 7^-3", "b": "1/343"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^6 ÷ 3^4", "b": "3^2 = 9"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (2^2)^5", "b": "2^10 = 1024"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^3 × 10^-2", "b": "10^1 = 10"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 6^-3", "b": "1/216"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 5^5 ÷ 5^2", "b": "5^3 = 125"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (4^4)^2", "b": "4^8 = 65536"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^7 × 2^-3", "b": "2^4 = 16"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^3 ÷ 3^1", "b": "3^2 = 9"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 7^0", "b": "1"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^4 × 10^-3", "b": "10^1 = 10"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (5^3)^3", "b": "5^9 = 1953125"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^-4", "b": "1/256"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^2 × 2^5", "b": "2^7 = 128"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 6^5 ÷ 6^3", "b": "6^2 = 36"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (3^5)^2", "b": "3^10 = 59049"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^-3", "b": "1/1000"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 7^3 × 7^-1", "b": "7^2 = 49"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^6 ÷ 4^4", "b": "4^2 = 16"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (2^6)^2", "b": "2^12 = 4096"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 5^-5", "b": "1/3125"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^2 × 3^4", "b": "3^6 = 729"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 6^0", "b": "1"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^5 × 10^-2", "b": "10^3 = 1000"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (4^5)^2", "b": "4^10 = 1048576"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 7^5 ÷ 7^3", "b": "7^2 = 49"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^-5", "b": "1/32"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^7 × 3^-3", "b": "3^4 = 81"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 5^4 ÷ 5^1", "b": "5^3 = 125"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (6^2)^3", "b": "6^6 = 46656"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^0", "b": "1"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^3 × 4^2", "b": "4^5 = 1024"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^8 ÷ 2^5", "b": "2^3 = 8"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (7^3)^2", "b": "7^6 = 117649"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^-6", "b": "1/729"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 5^2 × 5^3", "b": "5^5 = 3125"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 6^4 × 6^-2", "b": "6^2 = 36"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (10^3)^2", "b": "10^6 = 1000000"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^-5", "b": "1/1024"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 2^4 ÷ 2^1", "b": "2^3 = 8"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 7^6 ÷ 7^4", "b": "7^2 = 49"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (3^3)^3", "b": "3^9 = 19683"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 5^-4", "b": "1/625"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 6^3 × 6^2", "b": "6^5 = 7776"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 10^6 ÷ 10^3", "b": "10^3 = 1000"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (2^7)^2", "b": "2^14 = 16384"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 4^2 ÷ 4^0", "b": "4^2 = 16"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 3^5 × 3^-2", "b": "3^3 = 27"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: 7^2 × 7^3", "b": "7^5 = 16807"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "e", "f": "Simplify: (5^4)^2", "b": "5^8 = 390625"},
          
              // 7. fx (30 questions)
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(2) if f(x) = 3x + 1", "b": "7"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(-1) if f(x) = x^2 - 2", "b": "-1"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "What is the gradient of f(x) = 2x + 5?", "b": "2"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the y-intercept of f(x) = 4x - 3", "b": "-3"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(0) if f(x) = 5 - x", "b": "5"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the x-intercept of f(x) = 2x - 6", "b": "3"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(3) if f(x) = 2x - 1", "b": "5"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "What is the gradient of f(x) = -3x + 4?", "b": "-3"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the y-intercept of f(x) = 5x + 2", "b": "2"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(-2) if f(x) = x^2 + 1", "b": "5"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the x-intercept of f(x) = 3x - 9", "b": "3"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(1) if f(x) = 4x - 2", "b": "2"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "What is the gradient of f(x) = x - 7?", "b": "1"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the y-intercept of f(x) = -2x + 6", "b": "6"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(0) if f(x) = x^2 - 4", "b": "-4"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the x-intercept of f(x) = 5x - 10", "b": "2"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(4) if f(x) = 2x + 3", "b": "11"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "What is the gradient of f(x) = 4 - 3x?", "b": "-3"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the y-intercept of f(x) = 6x - 1", "b": "-1"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(-3) if f(x) = x^2 + 2", "b": "11"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the x-intercept of f(x) = 4x - 8", "b": "2"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(5) if f(x) = 3x - 5", "b": "10"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "What is the gradient of f(x) = 5x + 3?", "b": "5"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the y-intercept of f(x) = x + 4", "b": "4"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(2) if f(x) = x^2 - 3", "b": "1"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the x-intercept of f(x) = 2x - 4", "b": "2"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(-1) if f(x) = 5x + 1", "b": "-4"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "What is the gradient of f(x) = -x + 2?", "b": "-1"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find the y-intercept of f(x) = 3x - 6", "b": "-6"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "fx", "f": "Find f(0) if f(x) = 2x + 7", "b": "7"},
          
              // 8. f (10 questions)
              {"s": "M", "c": "CAPS", "l": "G10", "t": "f", "f": "Calculate simple interest: R500 at 5% p.a. for 2 years", "b": "R50"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "f", "f": "Find the total amount: R1000 at 3% p.a. simple interest for 3 years", "b": "R1090"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "f", "f": "What is 10% of R200?", "b": "R20"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "f", "f": "Calculate simple interest: R2000 at 4% p.a. for 1 year", "b": "R80"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "f", "f": "Find the principal if interest is R60 at 6% p.a. for 2 years", "b": "R500"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "f", "f": "What is the total after 5% discount on R400?", "b": "R380"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "f", "f": "Calculate simple interest: R1500 at 2% p.a. for 4 years", "b": "R120"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "f", "f": "Find the total amount: R300 at 8% p.a. simple interest for 2 years", "b": "R348"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "f", "f": "What is 15% of R600?", "b": "R90"},
              {"s": "M", "c": "CAPS", "l": "G10", "t": "f", "f": "Calculate the discount: 20% off R250", "b": "R50"}
    ]
  }
  